SME_WEB_ApiManagement/SME_WEB_ApiManagement/Controllers/ErrorAPIController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SME_WEB_ApiManagement.DAO;
using SME_WEB_ApiManagement.Models;
using SME_WEB_ApiManagement.Services;

namespace SME_WEB_ApiManagement.Controllers
{
    public class ErrorAPIController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<ErrorAPIController> _logger;
        protected static string API_Path_Main;
        protected static string API_Path_Sub;
        protected static string API_Path_Trigger;
        protected static string API_Path_Sub_Trigger;
        private readonly IWebHostEnvironment _webHostEnvironment;
        protected int currentPageNumber;
        protected static int PageSize;
        protected static int PageSizMedium;
        private readonly CallAPIService _callAPIService;
        public ErrorAPIController(ILogger<ErrorAPIController> logger,
            IConfiguration configuration, IWebHostEnvironment webHostEnvironment
             , CallAPIService callAPIService)

        {
            _logger = logger;
            _configuration = configuration;
            API_Path_Main = _configuration.GetValue<string>("API_Path_Main");
            API_Path_Sub = _configuration.GetValue<string>("API_Path_Sub");
            API_Path_Trigger = _configuration.GetValue<string>("API_Path_Trigger");
            API_Path_Sub_Trigger = _configuration.GetValue<string>("API_Path_Sub_Trigger");
            PageSize = _configuration.GetValue<Int32>("PageSize");
            PageSizMedium = _configuration.GetValue<Int32>("PageSizMedium");
            currentPageNumber = 1;
            _webHostEnvironment = webHostEnvironment;
            _callAPIService = callAPIService;

        }
        public IActionResult Index(ViewErroApiModels vm, string previous, string first, string next, string last, string hidcurrentpage, string hidtotalpage,
            string searchData = null, string clearSearcData = null, string DeleteData = null, string saveData = null, string cancelData = null, string editData = null)
        {
            #region panging
            int curpage = 0;
            int totalpage = 0;

            if (!string.IsNullOrEmpty(hidcurrentpage)) curpage = Convert.ToInt32(hidcurrentpage);
            if (!string.IsNullOrEmpty(hidtotalpage)) totalpage = Convert.ToInt32(hidtotalpage);
            if (!string.IsNullOrEmpty(first)) currentPageNumber = 1;
            else if (!string.IsNullOrEmpty(previous)) currentPageNumber = (curpage == 1) ? 1 : curpage - 1;
            else if (!string.IsNullOrEmpty(next)) currentPageNumber = (curpage == totalpage) ? totalpage : curpage + 1;
            else if (!string.IsNullOrEmpty(last)) currentPageNumber = totalpage;

            int PageSizeDummy = PageSize;
            int totalCount = 0;
            PageSize = PageSizeDummy;
            #endregion End panging

            ViewErroApiModels result = new ViewErroApiModels();
            try
            {
                if (!string.IsNullOrEmpty(searchData))
                {
                   var lerror = ErrorApiDAO.GetErrorApiBySearch(vm.ErrorModel, API_Path_Main + API_Path_Sub, null);
                    result.LError = lerror.LError;

                    result.PageModel = Service_CenterDAO.LoadPagingViewModel(lerror.totalList??0, currentPageNumber, PageSize);
                    result.totalList = lerror.totalList ?? 0;
                }
                else 
                {
                    TErrorApiLogModels model = new TErrorApiLogModels();

                    var lerror = ErrorApiDAO.GetErrorApiBySearch(model, API_Path_Main + API_Path_Sub, "N", currentPageNumber, PageSize, null);
                    result.LError = lerror.LError;
                    result.PageModel = Service_CenterDAO.LoadPagingViewModel(lerror.totalList ?? 0, currentPageNumber, PageSize);
                    result.totalList = lerror.totalList ?? 0;


                }

 
                result.LSystem = SystemDAO.GetSystem(API_Path_Main + API_Path_Sub, null);

                var serviceCenter = new ServiceCenter(_configuration, _callAPIService);
            
              
                return View(result);
            }
            catch (Exception ex)
            {
                return View(result);
            }
        }


        [HttpPost]
        public JsonResult DeleteSystem(int id)
        {
            // ลบข้อมูลจากฐานข้อมูลหรือ DAO
            // ตัวอย่าง: สมมติว่ามี ErrorModelDAO.DeleteSystemById
            string result = ErrorApiDAO.DeleteSystem(id.ToString(), API_Path_Main + API_Path_Sub, null);
            if (!string.IsNullOrEmpty(result))
                return Json(new { success = true });
            else
                return Json(new { success = false, message = "ไม่พบระบบหรือเกิดข้อผิดพลาด" });
        }

    }
}

SME_WEB_ApiManagement/SME_WEB_ApiManagement/Views/ErrorApi/Index.cshtml
@model SME_WEB_ApiManagement.Models.ViewErroApiModels
@{
    ViewData["Title"] = "Error list";
 
    
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>





@using (Html.BeginForm("Index", "ErrorAPI", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
{
    <div class="wrap-all-content">
        <!-- Search Card -->
        <div class="card-custom">
            <div class="card-title">ค้นหาระบบ Error list</div>
            <div class="row mb-3">
                <div class="col-md-6 mb-3">
                    <label class="form-label">ชื่อระบบ</label>
                    <input class="form-control" type="text" asp-for="ErrorModel.Message" placeholder="กรุณาระบุ" />
                </div>
                <div class="col-md-6 mb-3">
                    <label class="form-label">ระบบ</label>
                    <div class="input-group">
                        <select asp-for="ErrorModel.SystemCode"
                                asp-items="@(Model.LSystem.Select(system => new SelectListItem
                                {
                                    Text = system.SystemName,
                                    Value = system.SystemCode
                                }))"
                            class="form-select">
                        <option value="">--เลือก--</option>
                    </select>
                    
                    </div>
                </div>
            
            </div>
            <div class="d-flex justify-content-center mt-2">
                <button class="btn btn-outline-primary btn-custom" name="clearSearcData" id="clearSearcData" value="clearSearcData" type="submit">ล้างข้อมูล</button>
                <button class="btn btn-primary btn-custom" name="searchData" id="searchData" value="searchData" type="submit">ค้นหา</button>
            </div>
        </div>

        <!-- Table Card -->
        <div class="card-custom">
            <div class="d-flex justify-content-between align-items-center mb-3">
                <div class="card-title mb-0">รายการระบบ Error list</div>
            
            </div>
            <div class="table-responsive">
                <table class="table table-custom table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 60px;">ลำดับ</th>
                            <th>ชื่อระบบ</th>
                            <th >ชื่อ API</th>                          
                            <th >API Key</th>
                           
                            <th >HTTP</th>
                            <th>รายละเอียด</th>
                            <th >วันที่ Error</th>
                          
                        </tr>
                    </thead>
                    <tbody>

                        @if (Model.LError != null && Model.LError.Any())
                        {
                            var index = 1 + ((Model.PageModel.CurrentPageNumber - 1) * Model.PageModel.PageSize);
                            foreach (var w in Model.LError)
                            {
                                <tr>
                                    <td>@index</td>
                                    <td>@w.SystemName</td>
                                    <td>@w.SystemCode</td>
                                    <td>@w.ApiKey</td>
                                    <td>@w.HttpCode</td>
                                    <td>
                                        @(string.IsNullOrEmpty(w.Message)
                                                                    ? ""
                                                                    : (w.Message.Length > 100
                                                                    ? w.Message.Substring(0, 100) + "..."
                                                                    : w.Message))
                        </td>
                                    <td>@(w.Createdate.HasValue? w.Createdate.Value.ToString("dd/MM/yyyy HH:mm:ss") : "-")</td>
                             
                                </tr>
                                index++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="6" class="text-center">ไม่พบข้อมูล</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="table-footer">
                <div class="pagination-custom">
                    <button type="submit" class="btn btn-light" name="first" value="first" title="หน้าแรก"><i class="fa fa-angle-double-left"></i></button>
                    <button type="submit" class="btn btn-light" name="previous" value="previous" title="ก่อนหน้า"><i class="fa fa-angle-left"></i></button>
                    <span>Page</span>
                    <input type="text" name="hidcurrentpage" id="hidcurrentpage" value="@Model.PageModel.CurrentPageNumber" readonly />
                    <span>of @Model.PageModel.TotalPage</span>
                    <button type="submit" class="btn btn-light" name="next" value="next" title="ถัดไป"><i class="fa fa-angle-right"></i></button>
                    <button type="submit" class="btn btn-light" name="last" value="last" title="หน้าสุดท้าย"><i class="fa fa-angle-double-right"></i></button>
                </div>
                <div>
                    แสดง @((Model.LSystem?.Count() ?? 0) > 0 ? $"{1 + ((Model.PageModel.CurrentPageNumber - 1) * Model.PageModel.PageSize)} - {((Model.PageModel.CurrentPageNumber - 1) * Model.PageModel.PageSize) + Model.LSystem.Count()} จาก {Model.PageModel.TotalPage} รายการ" : "0 รายการ")
                </div>
            </div>
          
        </div>


    </div>

}